"""001_initial_shops_voice_whatsapp_ai_audit

Revision ID: 5324c17f83b9
Revises: 
Create Date: 2026-05-20 12:14:34.882525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5324c17f83b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('wa_phone_number_id', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('owner_phone', name=op.f('uq_shops_owner_phone'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_audit_log_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_shop_id'), 'audit_log', ['shop_id'], unique=False)
    op.create_table('voice_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('wa_media_id', sa.String(length=200), nullable=True),
    sa.Column('r2_key', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript_raw', sa.Text(), nullable=True),
    sa.Column('transcript_language', sa.String(length=10), nullable=True),
    sa.Column('asr_provider', sa.String(length=30), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_voice_notes_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_notes'))
    )
    op.create_index(op.f('ix_voice_notes_shop_id'), 'voice_notes', ['shop_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('from_phone', sa.String(length=20), nullable=True),
    sa.Column('to_phone', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_whatsapp_messages_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_messages')),
    sa.UniqueConstraint('wa_message_id', name=op.f('uq_whatsapp_messages_wa_message_id'))
    )
    op.create_index(op.f('ix_whatsapp_messages_shop_id'), 'whatsapp_messages', ['shop_id'], unique=False)
    op.create_table('ai_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('voice_note_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_p', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_ai_interactions_shop_id_shops')),
    sa.ForeignKeyConstraint(['voice_note_id'], ['voice_notes.id'], name=op.f('fk_ai_interactions_voice_note_id_voice_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_interactions'))
    )
    op.create_index(op.f('ix_ai_interactions_shop_id'), 'ai_interactions', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interactions_shop_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.drop_index(op.f('ix_whatsapp_messages_shop_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_voice_notes_shop_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index(op.f('ix_audit_log_shop_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('shops')
    # ### end Alembic commands ###
